config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  get "home/about" => "home/about"
  
  resources :users do
   member do
     get :following, :follower 
    end
  end
  
  resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end
  
  post 'follow/:id' => 'relationships#follow', as: 'follow' 
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' 
  
  get 'search' => 'search#search'
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
   validates :comment, presence: true 
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save 
 
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy

  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment) 
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment-area.html.erb
<td>
  <% book_show.book_comments.each do |book_comment| %>
  <%= link_to user_path(book_show.user) do %>
  <%= attachment_image_tag book_show.user, :profile_image, size:'40x40', fallback: "no_image.jpg", size:'40x40' %>
  <% end %><br>
  <%= link_to book_show.user.name, user_path(book_show.user) %>
</td>
<td>
  <%= book_comment.comment %>
</td>
<td>
  <% if book_comment.user == current_user %>
  <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: 'btn btn-danger btn-sm'%>
  <% end %>
  <% end %>
</td>

　　

app/views/book_comments/create.js.erb
$("#comment-area-<%= @book.id %>").html("<%= escape_javascript(render partial: 'book_comments/comment-area', locals: {book_show: @book, book_comment: @book_comment}) %>");
$('textarea').val('')  

app/views/book_comments/destroy.js.erb
$("#comment-area-<%= @book.id %>").html("<%= escape_javascript(render partial: 'book_comments/comment-area', locals: {book_show: @book, book_comment: @book_comment}) %>"); 