config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  get "home/about" => "home/about"
  
  resources :users do
   member do
     get :following, :follower 
    end
  end
  
  resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end
  
  post 'follow/:id' => 'relationships#follow', as: 'follow' 
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' 
  
  get 'search' => 'search#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy 
  has_many :book_comments, dependent: :destroy
  
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  
  attachment :image
  attachment :profile_image
  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  def aleady_favorited?(book) 
    self.favorites.exists?(book_id: book.id)
  end
  
  def follow(user_id)
  follower.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
  follower.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
  following_user.include?(user)
  end

  
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new 
  end
  
  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end
   
  def edit
    @user = User.find(params[:id])
    @user_new = User.new
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)  
    end
  end
  
  def new
    @book = Book.new
  end
  
  def create
    @user = User.new(user_params)
    @user.create(user_params)
    if @user.save
      redirect_to user_path(@user.id), notice: 'You have create user successfully'
    else
      render :root
    end
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to user_path(@user.id), notice: 'You have update user successfully'
    else
      render :edit
    end
  end
   
  def following
    @user  = User.find(params[:id])
    render 'show_follow'
  end

  def follower
    @user  = User.find(params[:id])
    render 'show_follower'
  end
  
  def self.search(search,word)
    if search == "forward_match"
                        　　　@user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
                        　　　@user = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
                        　　　@user = User.where("#{word}")
    elsif search == "partial_match"
                        　　　@user = User.where("name LIKE?","%#{word}%")
    else
                        　　　@user = User.all
    end
  end

 
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_error.html.erb
<% if @user.errors.any? %>
        <%= @user.errors.count %>errors prohibited this book from being saved:<br>
        <% @user.errors.full_messages.each do |message| %>
        <div class = "devise-error-messages"><%= message %></div><br>
        <% end %>
        <% end %>

app/views/users/_list.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <div class = "notice"><%= notice %></div>
        <% if @book.errors.any? %>
        <%= @book.errors.count %>errors prohibited this book from being saved:<br>
        <% @book.errors.full_messages.each do |message| %>
        <div class = "devise-error-messages"><%= message %></div><br>
        <% end %>
        <% end %>
        
        <h2>User info</h2>
        <%= attachment_image_tag user, :profile_image, size:'100x100', fallback: "no_image.jpg", size:'100x100' %>
        <table class>
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th class="profile-name"><%= user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= user.introduction %></th>
            </tr>
            <tr>
              <th>follows</th>
              <th><%= link_to user.follower.count, following_user_path(@user) %></th>
            </tr>
            <tr>
              <th>follower</th>
              <th><%= link_to user.followed.count, follower_user_path(@user) %></th> 
            </tr> 
          </tbody>
        </table>
        <% if @user.id == current_user.id %> 
        <div class="row">
　　　　　<%= link_to "", edit_user_path(user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
          </div>
        <% end %>  
          
        <div class = "row">
          <% unless current_user == user %> 
              <% if current_user.following?(user) %>
                  <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST, class:'btn btn-info btn-sm' %>
              <% else %>
                  <%= link_to 'フォローする', follow_path(user.id), method: :POST, class: 'btn btn-success btn-sm' %>
              <% end %>
          <% end %>
        </div>
           
        <h2 class="mt-3">New book</h2>
        <%= form_with model:@book, local:true do |f| %>
           <p>Title</p>
            <%= f.text_field :title %>
            <p>Opinion</p>
            <%= f.text_area :body %><br>
            <button class = "btn btn-success">Create Book</button> 
            <% end %>
      </div>

app/views/users/edit.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <%= form_with model:@user, local:true do |f| %>
      <h2>User info</h2>
      <div class = "form-group">
        <%= f.label :name, 'name' %>
        <%= f.text_field :name, class: 'form-control'%>
      </div>
      
      <%= render 'users/error', user: @user %>
        
      <div class = "form-group">
        <label for = "profil_image">image</label><br>
        <%= f.attachment_field :profile_image %>
      </div>
      <div class = "form-group">
        <%= f.label :introduction, 'introduction' %>
        <%= f.text_field :introduction, class: 'form-control' %>
      </div>
      <div class = "form-group">
        <button class = "btn btn-secondary">Update User</button>
      </div>
      <% end %>
  </div>
</div> 

app/views/users/index.html.erb
<%= render 'users/list', user: @user %>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, size:'40x40', fallback: "no_image.jpg", size:'40x40' %></td>
              <td><%= user.name %></td> 
              <td>
                <p>フォロー数：<%= user.follower.count %></p>
              </td>
              <td>
                <p>フォロワー数：<%= user.followed.count %></p>
              </td>
              <td> 
               <% unless current_user == user %>  
                  <% if current_user.following?(user) %>
                      <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
                  <% else %> 
                      <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
                  <% end %> 
               <% end %>
              </td> 
              <td><%= link_to "Show", user_path(user) %></td>
            </tr>
            <% end %>
          </tbody> 
        </table>
      </div>
    </div>
  </div> 
</main>

app/views/users/show.html.erb
<%= render 'users/list', user: @user %>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan = "3"></th>
          </thead>
          <tbody>　
             <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id)do %>
                <%= attachment_image_tag book.user, :profile_image, size:'40x40', fallback: "no_image.jpg", size:'40x40' %>
                <% end %>
              </td>
              <td><%= link_to book.title, book %></td>
              <td><%= book.body %></td>
              <td>    
                <p>コメント数：<%= book.book_comments.count %></p>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show_follow.html.erb
<h2>Follow User</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
    </tr>
  </thead>
  <tbody>
    <% @user.following_user.where.not(id: current_user.id).each do |user| %>
    <tr>
      <td>
        <%= attachment_image_tag user, :profile_image, size:'40x40', fallback: "no_image.jpg", size:'40x40' %>
      </td>
      <td>
        <%= user.name %>
      </td>
      <td>
        <p>フォロー数：<%= user.follower.count %></p>
      </td>
      <td>
        <p>フォロワー数：<%= user.followed.count %></p>
      </td>
      <td>
        <%= link_to "show", user_path(user) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show_follower.html.erb
<h2>Followe User</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
    </tr>
  </thead>
  <tbody>
    <% @user.follower_user.where.not(id: current_user.id).each do |user| %>
    <tr> 
      <td>
        <%= attachment_image_tag user, :profile_image, size:'40x40', fallback: "no_image.jpg", size:'40x40' %>
      </td>
      <td>
        <%= user.name %> 
      </td>
      <td>
        <p>フォロー数：<%= user.follower.count %></p>
      </td>
      <td>
        <p>フォロワー数：<%= user.followed.count %></p>
      </td>
      <td>
        <%= link_to "show", user_path(user) %>
      </td>
    </tr>
    <% end %> 
  </tbody>
</table>