config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  get "home/about" => "home/about"
  
  resources :users do
   member do
     get :following, :follower 
    end
  end
  
  resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end
  
  post 'follow/:id' => 'relationships#follow', as: 'follow' 
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' 
  
  get 'search' => 'search#search'
end

app/models/book.rb
class Book < ApplicationRecord
   
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   
  def new
    @book = Book.new
  end

  def create
    @books = Book.all 
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have create book successfully'
    else
      render :'users/show'
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end
  
  def show
    @book_show = Book.find(params[:id])
    @user = @book_show.user
    @book = Book.new
    @book_comment = BookComment.new
  end
  
  def edit 
    @book = Book.find(params[:id])
    if @book.user == current_user
       render "edit"
    else
       redirect_to books_path
    end
  end
  
  def update
    @user = current_user 
    @book = Book.find(params[:id])
    @book.update(book_params)
    @book.user_id = current_user.id
    if @book.save
        redirect_to book_path(@book.id), notice:'You have update book successfully'
    else
        render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  def self.search(search, word)
        if search == "forward_match"
                        @book = Book.where("title LIKE?","#{word}%")
        elsif search == "backward_match"
                        @book = Book.where("title LIKE?","%#{word}")
        elsif search == "perfect_match"
                        @book = Book.where("#{word}")
        elsif search == "partial_match"
                        @book = Book.where("title LIKE?","%#{word}%")
        else
                        @book = Book.all
        end
  end
  
   private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_eroorb.html.erb
<% if book.errors.any? %>
        <%= book.errors.count %>errors prohibited this book from being saved:<br>
        <% book.errors.full_messages.each do |message| %>
        <%= message %><br>
        <% end %>
        <% end %>

app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user)%>
  <p>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    ♥<%= book.favorites.count %>  
    <% end %>  
  </p>
    <% else %> 
  <p>
     <%= link_to book_favorites_path(book), method: :post, remote: true do %>
     ♡<%= book.favorites.count %>
    <% end %> 
  </p>
<% end %> 

app/views/books/edit.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= form_with model:@book, local:true do |f| %>
      
       <% if @book.errors.any? %>
        <%= @book.errors.count %>errors prohibited this book from being saved:<br>
        <% @book.errors.full_messages.each do |message| %>
        <%= message %><br>
        <% end %>
        <% end %>
      
      <h1>Editing Book</h1>
      <div class = "form-group">
        <%= f.label :title, 'title' %>
        <%= f.text_field :title, class: 'form-control'%>
      </div>
      <div class = "form-group">
        <%= f.label :body, 'Opinion' %>
        <%= f.text_field :body, class: 'form-control' %>
      </div>
      <div class = "form-group">
        <button class = "btn btn-success">Update Book</button>  
        <br> 
        <br>
        <%= link_to "Show", book_path(@book) %>
        |
        <%= link_to "Back", books_path %> 
      </div>
      <% end %>
    </div> 
  </div>
</div>

app/views/books/index.html.erb
<%= render 'users/list', user: @user %>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th colspan="3"></th>
          </tr>
          </thead>
          <tbody>  
            <% @books.each do |book| %>    
            <tr>
              <td>
                <%= link_to user_path(book.user.id)do %>
                 <%= attachment_image_tag book.user, :profile_image, size:'40x40', fallback: "no_image.jpg", size:'40x40' %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td id="favorite-btn-<%= book.id %>"> 
                  <%= render 'favorites/favorite-btn', book: book %>
              </td>
              <td>  
                 <p>コメント数：<%= book.book_comments.count %></p>
              </td>
            </tr> 
            <% end %> 
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<%= render 'users/list', user: @user %> 
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            
            <tr>
              <td><%= link_to user_path(@book_show.user) do %>
                <%= attachment_image_tag @book_show.user, :profile_image, size:'40x40', fallback: "no_image.jpg", size:'40x40' %>
                <% end %><br>
                <%= link_to @book_show.user.name, user_path(@book_show.user) %>
              </td> 
              <td><%=link_to @book_show.title, book_path(@book_show.user) %></td>
              <td><%= @book_show.body %></td> 
              <td id="favorite-btn-<%= @book_show.id %>">
                  <%= render 'favorites/favorite-btn', book: @book_show %>
              </td>
              <td> 
              <p>コメント数：<%= @book_show.book_comments.count %></p>
              </td>
              <% if @user.id == current_user.id %>
             <td><%= link_to "Edit", edit_book_path(@book_show), class: 'btn btn-success btn-sm' %></td>
             <td><%= link_to "Destroy", book_path(@book_show), method: :delete, "data-confirm" => "本当に消しますか", class: 'btn btn-danger btn-sm'%></td>
              
            <% end %>
            
            <div id="comment-area-<%= @book_show.id %>">
              <%= render 'book_comments/comment-area', book_show: @book_show, book_comment: @book_comment %>
            　<td>
                <%= form_with model:[@book_show, @book_comment], remote: true do |f| %>
                <%= f.text_area :comment, rows:'5' %> 
                <%= f.submit "送信" %> 
                <% end %>
              </td>
            </div>

            
            </tr>  
            
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>