config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  get "home/about" => "home/about"
  
  resources :users do
   member do
     get :following, :follower 
    end
  end
  
  resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end
  
  post 'follow/:id' => 'relationships#follow', as: 'follow' 
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' 
  
  get 'search' => 'search#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
   validates :comment, presence: true 
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User" 
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy 
  has_many :book_comments, dependent: :destroy
  
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  
  attachment :image
  attachment :profile_image
  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  def aleady_favorited?(book) 
    self.favorites.exists?(book_id: book.id)
  end
  
  def follow(user_id)
  follower.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
  follower.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
  following_user.include?(user)
  end

  
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   
  def new
    @book = Book.new
  end

  def create
    @books = Book.all 
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have create book successfully'
    else
      render :'users/show'
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end
  
  def show
    @book_show = Book.find(params[:id])
    @user = @book_show.user
    @book = Book.new
    @book_comment = BookComment.new
  end
  
  def edit 
    @book = Book.find(params[:id])
    if @book.user == current_user
       render "edit"
    else
       redirect_to books_path
    end
  end
  
  def update
    @user = current_user 
    @book = Book.find(params[:id])
    @book.update(book_params)
    @book.user_id = current_user.id
    if @book.save
        redirect_to book_path(@book.id), notice:'You have update book successfully'
    else
        render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  def self.search(search, word)
        if search == "forward_match"
                        @book = Book.where("title LIKE?","#{word}%")
        elsif search == "backward_match"
                        @book = Book.where("title LIKE?","%#{word}")
        elsif search == "perfect_match"
                        @book = Book.where("#{word}")
        elsif search == "partial_match"
                        @book = Book.where("title LIKE?","%#{word}%")
        else
                        @book = Book.all
        end
  end
  
   private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    
  end
 
  def destroy 
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  
  def about
  end
  
  def show
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
  def show
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def search
    @range = params[:range]
    search = params[:search]
    word = params[:word] 
    
    if @range == '1'
      if search == "forward_match"
         @users = User.where("name LIKE ?", "#{word}%") 
      elsif search == "backward_match" 
         @users = User.where("name LIKE ?", "%#{word}")
      elsif search == "perfect_match"
         @users = User.where("name LIKE ?", "#{word}") 
      elsif search == "partial_match"
         @users = User.where("name LIKE ?", "%#{word}%")
      else
         @users = User.all 
      end
     
    else
      if search == "forward_match"
         @books = Book.where("title LIKE ?", "#{word}%") 
      elsif search == "backward_match"
         @books = Book.where("title LIKE ?", "%#{word}")
      elsif search == "perfect_match" 
         @books = Book.where("title LIKE ?", "#{word}")
      elsif search == "partial_match"
         @books = Book.where("title LIKE ?", "%#{word}%")
      else
         @books = Book.all 
      end
      
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new 
  end
  
  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end
   
  def edit
    @user = User.find(params[:id])
    @user_new = User.new
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)  
    end
  end
  
  def new
    @book = Book.new
  end
  
  def create
    @user = User.new(user_params)
    @user.create(user_params)
    if @user.save
      redirect_to user_path(@user.id), notice: 'You have create user successfully'
    else
      render :root
    end
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to user_path(@user.id), notice: 'You have update user successfully'
    else
      render :edit
    end
  end
   
  def following
    @user  = User.find(params[:id])
    render 'show_follow'
  end

  def follower
    @user  = User.find(params[:id])
    render 'show_follower'
  end
  
  def self.search(search,word)
    if search == "forward_match"
                        　　　@user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
                        　　　@user = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
                        　　　@user = User.where("#{word}")
    elsif search == "partial_match"
                        　　　@user = User.where("name LIKE?","%#{word}%")
    else
                        　　　@user = User.all
    end
  end

 
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<header>
  <nav class = "navbar navbar-expand-lg navbar-dark bg-dark">
    <div class = "container">
      <div class = "navbar-brand">
        <%= link_to "Bookers", '/', class: 'text-white'%>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class = "collapse navbar-collapse" id = "navbarNavDolopdown">
        <ul class = "navbar-nav ml-auto">
           <% if user_signed_in? %>
          <li> 
            <%= link_to ' Home', user_path(current_user.id), class: 'fas fa-home nav-link text-ligh text-white' %>
          </li>
          <li>
            <%= link_to ' Users', users_path, class: 'fas fa-users nav-link text-light text-white' %>
          </li>
          <li>
            <%= link_to ' Books', books_path, class: 'fas fa-book-open nav-link text-light text-white' %>
          </li>
          <li>
            <%= link_to ' logout', destroy_user_session_path, method: :delete , class: 'fas fa-sign-out-alt nav-link text-light text-white'%>
          </li>
          <% else %>
          <li>
            <%= link_to ' Home', '/', class: 'fas fa-home nav-link text-light text-white' %>
          </li> 
          <li>
            <%= link_to " About", "/home/about", class: 'fas fa-link nav-link text-light text-white' %> 
          </li>
          <li>
            <%= link_to " sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light text-white' %>
          </li>
          <li>
            <%= link_to " login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light text-white' %>
          </li>
            <% end %>
        </ul>
      </div>
    </div>
  </nav>  
    
  <% if user_signed_in? %> 
    <%= form_with url: search_path, method: :get, local: true do |f| %>  
       <%= f.text_field :word %>
       <%= f.select :range ,options_for_select([ ['User', '1'], ['Book', '2']]) %>
       <%= f.select :search, options_for_select([["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
       <%= f.submit "検索" %>
    <% end %>
  <% end %> 
</header>
<br>
    <%= yield %>
    <footer> 
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight infratop.inc</p>
      </div>
    </div>
  </div>
</footer>
  </body>
</html>